### ISSUE TITLE
NameError: uninitialized constant ActiveRecord::Associations::BelongsToPolymorphicAssociation

### ISSUE THREAD

**Issue by novito** [airblade/paper_trail#939] opened 2017-03-20 11:38 UTC
This error is not happening always, but I haven't been able to figure out any commonalities for the different times that have happened, despite the fact that they all come from the Product model when trying to load a specific version.  For some context, even though I don't know if it might be relevant, this is happening when we try to use that product method from within a Sidekiq worker.

I was not able to write a failing test for the issue :(. I am adding the stack trace after the issue template that I created:

# This is the template without a failing test.

```ruby
require "bundler/inline"
gemfile(true) do
  ruby "2.3.3"
  source "https://rubygems.org"
  gem "activerecord", "4.2.8"
  gem "minitest", "5.9.0"
  gem "paper_trail", "4.1.0", require: false
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = nil
ActiveRecord::Schema.define do
  create_table :products, force: true do |t|
    t.string :name, null: false
    t.float :white_cost_display, null: false
    t.float :color_cost_display, null: false
    t.timestamps null: false
  end

  create_table :colors, force: true do |t|
    t.string :name, null: false
    t.integer :product_id, null: false
    t.timestamps null: false
  end

  create_table :items, force: true do |t|
    t.string :name, null: false
    t.integer :color_id, null: false
    t.timestamps null: false
  end

  create_table :versions do |t|
    t.string :item_type, null: false
    t.integer :item_id, null: false
    t.string :event, null: false
    t.string :whodunnit
    t.text :object, limit: 1_073_741_823
    t.text :object_changes, limit: 1_073_741_823
    t.integer :transaction_id
    t.datetime :created_at
  end
  add_index :versions, [:item_type, :item_id]
  add_index :versions, [:transaction_id]
end
ActiveRecord::Base.logger = Logger.new(STDOUT)
require "paper_trail/config"
require "paper_trail"

class Product < ActiveRecord::Base
  has_many :colors
  has_many :items, through: :colors# This also has_paper_trail
  has_paper_trail only: [:white_cost_display, :color_cost_display]

  def load_version_at(time)
    if association(:versions).loaded?
      versions.detect { |v| v.created_at > time }.try(:reify)
    else
      version_at(time) # When going through this path, it blows up (sometimes)
    end
  end
end

class Color < ActiveRecord::Base
  has_many :items
  belongs_to :product
end

class Item < ActiveRecord::Base
  has_paper_trail
  belongs_to :color
  has_one :product, through: :color
end

product = Product.create(name: "Radio", white_cost_display: 20, color_cost_display: 10)
color = Color.create(name: "Blue", product_id: product.id)
Item.create(name: "Blue Radio", color_id: color.id)

product.load_version_at(Time.now)
```

# Stack trace

```
[GEM_ROOT]/gems/activerecord-4.2.8/lib/active_record/reflection.rb:451:in `association_class'
[GEM_ROOT]/gems/activerecord-4.2.8/lib/active_record/associations.rb:162:in `association'
[GEM_ROOT]/gems/activerecord-4.2.8/lib/active_record/associations/builder/association.rb:115:in `item'
[GEM_ROOT]/gems/paper_trail-4.1.0/lib/paper_trail/reifier.rb:37:in `reify'
[GEM_ROOT]/gems/paper_trail-4.1.0/lib/paper_trail/version_concern.rb:206:in `block in reify'
[GEM_ROOT]/gems/paper_trail-4.1.0/lib/paper_trail/version_concern.rb:285:in `without_identity_map'
[GEM_ROOT]/gems/paper_trail-4.1.0/lib/paper_trail/version_concern.rb:205:in `reify'
[GEM_ROOT]/gems/paper_trail-4.1.0/lib/paper_trail/has_paper_trail.rb:202:in `version_at'
[PROJECT_ROOT]/app/models/product.rb:337:in `load_version_at'
```

**Comment by jaredbeck** [comment] 2017-03-20 16:01
Hi Joan, can you reproduce this issue using the latest version of PT (currently 6.0.2)? The bug report template is a very convenient way to try different versions. Thanks.

**Comment by novito** [comment] 2017-03-20 16:08
@jaredbeck thank you for quick feedback. I already tried with latest version of PT and I was not able to reproduce. Notice that even with the version that I placed in the original bug I am not able to reproduce. I just see it in production, and not all the time. Is not consistent.

**Comment by jaredbeck** [comment] 2017-03-20 18:13
I see. If it can't be reproduced, I don't think we'll be able to help. If you can't reproduce it with the bug report template, how about with a sample app?

**Comment by novito** [comment] 2017-03-21 09:33
@jaredbeck I will see if I can reproduce it in a sample app, but I doubt it because I can't even reproduce it in my production systems. I've been trying to follow the stack trace to figure out why `ActiveRecord::Associations::BelongsToPolymorphicAssociation` would be uninitialized, but no luck at all.

**Comment by jaredbeck** [comment] 2017-03-27 05:13
> I will see if I can reproduce it in a sample app, but I doubt it because I can't even reproduce it in my production systems.

Well, thanks for trying. I'll close this for now, but please let us know if you find a way to reproduce the issue and we'll be happy to reopen it.

**Closed by jaredbeck** 2017-03-27 05:13 UTC
Labels: Need Information
