### ISSUE TITLE
Reifying has_many through associations help

### ISSUE THREAD

**Issue by magister94** [airblade/paper_trail#461] opened 2015-01-09 02:39 UTC
My associations aren't reverting. I must be doing something wrong. 
Here's a similar setup to mine. I'm using the latest master branch.

    class Ball < ActiveRecord::Base
      has_many :ball_colors
      has_many :colors, through: :ball_colors
      has_paper_trail
    end

    class BallColor < ActiveRecord::Base
      belongs_to :ball 
      belongs_to :color
      has_paper_trail
    end

    class Color < ActiveRecord::Base
      has_paper_trail
      has_many :ball_colors
      has_many :balls, through: :ball_colors
    end

This is what I'm doing.

    ball = Ball.create()
    ball.name = 'Before I add color'
    ball.save
    
    ball.colors << Color.create(name: 'blue')
    ball.save #although this is unnecessary i think 

    ball.name = 'After adding color'
    ball.save

    b = ball.versions.last.reify(:has_many => true)
    b.save

    b.reload
    b.name  #=> 'Before I add color'
    b.colors #=> [Blue] 

b.colors should be empty.
Also, ball.versions doesn't include the change when I added a color to the ball. There's only create,  update for 'Before I add color', update for 'After adding color'.
Could someone tell me what I'm doing wrong or point me to an example? 
I've read the Associations section of the documentation but to no avail.

**Comment by batter** [comment] 2015-01-12 16:26
You added a color to the `b` object prior to making a new version, which explains why the `b.colors` is not empty when you reify the old version. If you had changed the order to be like this:

```ruby
ball.name = 'After adding color'
ball.save

ball.colors.create!(name: 'blue')
```

Then I would expect `b.colors` to be empty when you reified the older version.

You shouldn't expect to see an additional version for when you added an association to the ball, because you didn't change the object attributes at all before calling `save` there.  Versions only get generated for events where `save` actually persists a change to the root object itself.  It seems to me as though everything is working as I would expect it is, what didn't work the way you thought it would?

**Comment by magister94** [comment] 2015-01-12 17:29
Alright. I was expecting the wrong results.
After getting the proper version and associations back, I notice that when I save the reverted Ball object, the associations don't change in the database. I've tried adding (:mark_for_destruction => true) to the reify options but .save! still has no change to the associations. How can I make the reverted association I see in the object change in the database?

Also, if I wanted a change to a Color association to be versioned without changing the Ball object how should I go about it?

    ball.touch_with_version
    ball.colors << 'orange'

Would this be what is intended? 

Thanks for your help.

**Comment by jaredbeck** [comment] 2015-03-22 01:29
It sounds like this is a dupe of #463.  @magister94 do you mind if we close this issue and continue the conversation in #463?  Thanks.

**Closed** 2015-03-22 02:33 UTC
Labels: Not a bug

**Comment by nicolas-besnard** [comment] 2015-10-30 16:27
This is a dupe of #463 but #463 mention that #461 is a dupe of #643. Mind Blown !
