### ISSUE TITLE
Generator doesnt create migration for versions table

### ISSUE THREAD

**Issue by westonganger** [airblade/paper_trail#494] opened 2015-03-04 16:39 UTC
I was running the normal generator in Rails 3.2.13 and it does not create the migration(s). When running the  generator with the --with-associations flag it only generated the following migrations: CreateVersionAssociations and AddTransactionIdColumnToVersions which again is missing the other migration(s)

**Comment by westonganger** [comment] 2015-03-04 16:48
Update: seems like this was because the migration already existed in a previous migration. Maybe it would be good to show a message saying the migration already existed

**Comment by batter** [comment] 2015-03-20 03:46
Ok, so this is not a dupe of #459?  Not sure how to show a warning message for duplicate migrations. If you have knowledge of how that is possible then please make a pull request.

**Comment by westonganger** [comment] 2015-03-20 14:02
rails does it, i think we should be able to. Relevant Rails source code is here https://github.com/rails/rails/blob/b9fcce3944653db5eb49119c134e8525e91f7aee/railties/lib/rails/generators/actions/create_migration.rb

If i get a chance I will take a look

**Closed** 2015-03-20 22:50 UTC

**Comment by batter** [comment] 2015-03-20 22:54
Apologies @westonganger, a closer inspection at our migration generator found that this was actually not that difficult!
