### ISSUE TITLE
rails 4.2 + rails_admin - incorrect work of user email list

### ISSUE THREAD

**Issue by kpblc** [airblade/paper_trail#452] opened 2014-12-27 19:01 UTC
hello! after updating rails to 4.2 in rails_admin, instead showing user email, it's showing something like #<User:0x00000004a9df90>. in rails 4.1.8 all work correct. rails 4.2 is supported? if not, can you say, when you planing to include this version in supported.
P.S. in screenshot user name #<User:0x00000004a9df90> is for version rails 4.2, then i'll rollback and papertrail start to work correct and show 'admin@mail.com'

![paper_trail_problems](https://cloud.githubusercontent.com/assets/6714004/5562070/89d85aca-8e13-11e4-8d02-8c53e43857a3.png)

**Comment by batter** [comment] 2015-01-29 22:57
I'm closing this. If you find out the issue is actually something not working w/ PaperTrail, feel free to comment / re-open.

**Closed by batter** 2015-01-29 22:57 UTC
Labels: Third party issue
