### ISSUE TITLE
Metadata/info_for_paper_trail ignored on update

### ISSUE THREAD

**Issue by eliasmacedo** [airblade/paper_trail#612] opened 2015-09-08 20:18 UTC
I'm using *paper_trail (3.0.8)* and trying to use the **meta** option of *has_paper_trail* on the model as follows:
```
has_paper_trail :on => [:create, :update], 
                  :skip => [:info_a,:info_b], 
                  :meta => { :item_type  => 'Parent',
                             :item_id => :parent_id 
                           }
```
I'm also changing the event according to specific actions with *paper_trail_event*.
```
p.paper_trail_event = 'custom_event'
```

I'm implementing it to save some steps of the child's life cycle on the parent's log. So I need the *item_type* and *item_id* to refer to the **parent**.

This works as expected on *creation* but fails to give me the expected data on *update* and *destroy*. These actions seem to ignore the changes on *item_type* and *item_id* and save the *version* object with only the *event* changed. Example:
```
#create action
#v refers to the PaperTrail::Version object
puts v.item_type,v.item_id,v.event
#"Parent"
#100 #correct parent_id
#"custom_event"
```

```
#any update or destroy action
#v refers to the PaperTrail::Version object
puts v.item_type,v.item_id,v.event
#"Child"
#50936 #child_id
#"custom_event"
```

I'm thinking it may be a *"timing"* problem where it overwrites my changes, though it doesn't seem to be the expected behaviour, as it works on *creation* with no issues but seems to break on *updates*.

**shorter version:** Changing *item_type* and *item_id* from *PaperTrail::Version* through **metadata** or **info_for_paper_trail** on the controller doesn't work on *update/destroy*, it seems the changes are overwritten.

Should I override any methods to make it work like this?
Lastly, let me offer my thanks for the great work on this very useful gem and any help you can provide.

**Comment by jaredbeck** [comment] 2015-09-08 21:50
Thanks for the bug report.  Can you reproduce this issue in a new rails app?  If so, can you provide us with the smallest amount of code we can paste into a new rails app to reproduce the problem?  Or, better yet, can you add a failing test to our test suite?  Thanks.

**Comment by batter** [comment] 2015-09-08 23:58
I don't know that I would classify this as a "bug" really since the OP is attempting to use the gem in a manner that it wasn't designed to work with out of the box (albeit cleverly)

I'm guessing the order when metadata gets merged is slightly different for the create vs update callbacks. I'll take a closer look when I get a chance to confirm.

**Comment by eliasmacedo** [comment] 2015-09-09 16:24
Thanks for the replies. 

@jaredbeck, I can reproduce it on any new app on the version mentioned. But as @batter said, it's not necessarily a "bug" on *paper_trail*, since I'm taking a bit of creative liberty with it's usage.

I have figured out where it "breaks" and will explain it shortly in case it helps anyone who comes across the same issue.

I checked the flows and callbacks and noticed my custom set `:item_type` and `:item_id` keys were present and correctly set in all of them.
Everything worked as intended (with the custom metadata being preserved) until the end of the *before_update* callback as follows:

```
      def record_update
        if paper_trail_switched_on? && changed_notably?
          object_attrs = object_attrs_for_paper_trail(item_before_change)
          data = {
            :event     => paper_trail_event || 'update',
            :object    => self.class.paper_trail_version_class.object_col_is_json? ? object_attrs : PaperTrail.serializer.dump(object_attrs),
            :whodunnit => PaperTrail.whodunnit
          }

          if self.class.paper_trail_version_class.column_names.include?('object_changes')
            data[:object_changes] = self.class.paper_trail_version_class.object_changes_col_is_json? ? changes_for_paper_trail :
              PaperTrail.serializer.dump(changes_for_paper_trail)
          end
        ### 
        send(self.class.versions_association_name).build merge_metadata(data)
        ###
        end
      end
```
The line between **###** where *build* is called is where `:item_type` and `:item_id` are overwritten/removed. I believe this is standard behaviour for *active_record* on the version I am using.
I have changed that method slightly (to use *create!*) so I can make it work like I need, though I am aware it breaks the *reify* "magic".

Thanks again for the attention, I believe this issue can be closed.

**Comment by jaredbeck** [comment] 2015-09-09 17:46
> Thanks again for the attention, I believe this issue can be closed.

**Closed by jaredbeck** 2015-09-09 17:46 UTC
Labels: Need Information

**Comment by batter** [comment] 2015-09-09 22:13
@eliasmacedo - Yes I believe ActiveRecord will automatically override those column values to try to use the association defaults
