### ISSUE TITLE
support has and belongs to many associations

### ISSUE THREAD

**Issue by dgobaud** [airblade/paper_trail#565] opened 2015-07-10 02:59 UTC
the models/migrations https://gist.github.com/anonymous/2e3bc73df036e88a9b20

the errors https://gist.github.com/anonymous/b6a4f9cd49c3988edaf0

**Comment by jaredbeck** [comment] 2015-07-13 18:06
Thanks for the bug report.  It looks like you've done a great job boiling this down to a simple example.  Could you help us take the next step and turn this into a failing test in the PaperTrail test suite?  There's a "dummy" rails app at `test/dummy`.  You can add your models there, or use the existing models.  If you need migrations, add them to `test/dummy/db/migrate/20110208155312_set_up_test_tables.rb`.  The failing test can go in `spec/models`.  Thanks!

**Comment by jaredbeck** [comment] 2015-07-23 05:12
> Could you help us take the next step and turn this into a failing test in the PaperTrail test suite?

David, have you had time to give this a try?  We'd really appreciate the help.  Do you have any questions about how to do it?

**Comment by dgobaud** [comment] 2015-07-23 17:31
Sorry I haven't had time yet.

**Comment by jaredbeck** [comment] 2015-08-01 02:51
David, is there supposed to be a `ZipCode` model too? Also, can you reproduce this without the `rails_admin` stuff? Is that really part of the issue? Thanks!

**Comment by dgobaud** [comment] 2015-08-01 17:39
Removing rails_admin gem fixed the issue.

there is a zipcode model but it could be any model. it just has to be a model with a HABTM relationship

here is zip code model https://gist.github.com/anonymous/026ebeda53502b75b04e

**Comment by jaredbeck** [comment] 2015-08-04 14:26
> Removing rails_admin gem fixed the issue.

Great! I'll close the issue then.

**Closed by jaredbeck** 2015-08-04 14:26 UTC
Labels: Need Information

**Comment by jaredbeck** [comment] 2015-08-04 21:01
David, if you can reproduce this issue in a brand new rails app with the latest paper_trail and no rails_admin, please open a new issue, thanks!
