### ISSUE TITLE
The polymorphic `item` association should support nested AR classes

### ISSUE THREAD

**Issue by TangMonk** [airblade/paper_trail#739] opened 2016-03-23 09:24 UTC
I have following model:

```
class Businessman < ActiveRecord::Base
    has_paper_trail
end
```

```
class Businessman::Product < ActiveRecord::Base
    has_paper_trail
end
```

When I create `Businessman::Product` records, the `versions` table save `Businessman` instead of `Businessman::Product`

How to fix that? I am using 4.x paper_trail

**Comment by jaredbeck** [comment] 2016-03-23 15:40
> .. the versions table save Businessman instead of Businessman::Product ..

Does `versions.item_type == "Businessman"`? 

Have you tried a parent module instead of parent class?

```
module Foo
  class Product
    has_paper_trail
  end
end
```

**Comment by jaredbeck** [comment] 2016-03-23 16:33
Also, you have titled this issue "STI Problem" but the `has_many :versions` association is a *polymorphic* association. Where is STI involved?

**Comment by TangMonk** [comment] 2016-03-24 01:10
@jaredbeck sorry, this code should be:

```
class Businessman < ActiveRecord::Base
    has_paper_trail
end
```

```
class Businessman::Product < Businessman
    has_paper_trail
end
```

**Comment by jaredbeck** [comment] 2016-03-25 01:14
>>>      .. the versions table save Businessman instead of Businessman::Product ..
>>
>> Does versions.item_type == "Businessman"? 
>
> The item_type always Businessman

That's interesting, because `item_type` is set by `has_many` and I'll be really surprised if there's a bug in `has_many` :)

Please try to reproduce this using our [bug report template][1].

[1]: https://github.com/airblade/paper_trail/blob/master/doc/bug_report_template.rb

**Comment by TangMonk** [comment] 2016-03-25 03:31
@jaredbeck , thanks for your reply. I create a [demo project ](https://github.com/TangMonk/paper_trail_sti_issue) for reproduce , also as error template:

```
# Use this template to report PaperTrail bugs.
# It is based on the ActiveRecord template.
# https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_gem.rb
begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  ruby "2.2.3"
  source "https://rubygems.org"
  gem "activerecord", "4.2.0"
  gem "minitest", "5.8.3"
  gem "paper_trail", "4.0.0", require: false
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :users, force: true do |t|
    t.text :first_name, null: false
    t.timestamps null: false
  end
  create_table :versions do |t|
    t.string :item_type, null: false
    t.integer :item_id, null: false
    t.string :event, null: false
    t.string :whodunnit
    t.text :object, limit: 1_073_741_823
    t.text :object_changes, limit: 1_073_741_823
    t.integer :transaction_id
    t.datetime :created_at
  end
  add_index :versions, [:item_type, :item_id]
  add_index :versions, [:transaction_id]

  create_table :version_associations do |t|
    t.integer  :version_id
    t.string   :foreign_key_name, null: false
    t.integer  :foreign_key_id
  end
  add_index :version_associations, [:version_id]
  add_index :version_associations, [:foreign_key_name, :foreign_key_id],
    name: "index_version_associations_on_foreign_key"
end

# We must wait to require `paper_trail.rb` until after the
# `version_associations` table exists or else PT won't track associations.
require "paper_trail"

class User < ActiveRecord::Base
  has_paper_trail
end

class User::David < User
  has_paper_trail
end

class BugTest < ActiveSupport::TestCase
  def test_1
    b = User::David.create first_name: "David"
    assert_equal(b.versions.first.item_type, 'User::David') # it will fail
  end
end
```

**Comment by jaredbeck** [comment] 2016-03-25 16:16
>  I create a demo project for reproduce , also as error template

Thanks David! That's very helpful. I will mark this as a confirmed bug.

**Comment by TangMonk** [comment] 2016-03-26 02:18
@jaredbeck , Hi, I found similar issues on this project, seems i am not alone, https://github.com/airblade/paper_trail/issues?utf8=%E2%9C%93&q=sti

**Comment by jaredbeck** [comment] 2016-03-28 17:58
Our next step should be to convert your bug report script to a test in the PT test suite.

**Comment by batter** [comment] 2016-03-28 22:16
Understood that the example you provided with the template is a very simplistic case, but I'm not sure that ActiveRecord can differentiate in a case like this easily either. I say this because in the case provided, both record types are being inserted into the `users` table, so this also rings true:

```ruby
# Use this template to report PaperTrail bugs.
# It is based on the ActiveRecord template.
# https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_gem.rb
begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  ruby "2.2.3"
  source "https://rubygems.org"
  gem "activerecord", "4.2.0"
  gem "minitest", "5.8.3"
  gem "paper_trail", "4.0.0", require: false
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :users, force: true do |t|
    t.text :first_name, null: false
    t.timestamps null: false
  end
  create_table :versions do |t|
    t.string :item_type, null: false
    t.integer :item_id, null: false
    t.string :event, null: false
    t.string :whodunnit
    t.text :object, limit: 1_073_741_823
    t.text :object_changes, limit: 1_073_741_823
    t.integer :transaction_id
    t.datetime :created_at
  end
  add_index :versions, [:item_type, :item_id]
  add_index :versions, [:transaction_id]

  create_table :version_associations do |t|
    t.integer  :version_id
    t.string   :foreign_key_name, null: false
    t.integer  :foreign_key_id
  end
  add_index :version_associations, [:version_id]
  add_index :version_associations, [:foreign_key_name, :foreign_key_id],
    name: "index_version_associations_on_foreign_key"
end

# We must wait to require `paper_trail.rb` until after the
# `version_associations` table exists or else PT won't track associations.
require "paper_trail"

class User < ActiveRecord::Base
  has_paper_trail
end

class User::David < User
  has_paper_trail
end

class BugTest < ActiveSupport::TestCase
  def test_1
    b = User::David.create first_name: "David"
    assert_equal(User.last.attributes, User::David.last.attributes)
  end

  def test_2
    assert_equal(User.table_name, User::David.table_name)
  end
end
```

What I'm saying, is that there is only 1 record at the database level in this case, but because of the funky way you setup the housing of one model inside the other, ActiveRecord / Ruby allows you to evaluate it in runtime as if there are different types of records, but in reality, it is the same entry at the database level. I'm just wondering what the use-case is, since this seems like an attempt to almost hack PaperTrail into returning special in memory object wrappers around database rows that otherwise would not be able to differentiate themselves from each other, correct?

Unless you also have a `type` column at the database level in your real life example, which is not being provided in this example.

**Comment by batter** [comment] 2016-03-28 22:21
Also, for historical context, the original incarnation of how it determines which class name to insert dates all the way back to #167, which was done to accommodate inheritance in ActiveRecord classes in more traditional single table inheritance setups. Your setup seems more unique than most in that you are using a combination of single table inheritance and namespacing.

**Comment by TangMonk** [comment] 2016-03-30 07:21
@batter thanks for your reply, I am sorry for the mistake in template, I miss the type field on the users table, it not real code, But you can checkout my [test project](https://github.com/TangMonk/paper_trail_sti_issue)

**Comment by jaredbeck** [comment] 2016-03-30 19:40
> I am sorry for the mistake in template, I missing the type field on the users table, it not real code, But you can checkout my test purpose project

In David's [test project](https://github.com/TangMonk/paper_trail_sti_issue) the models are defined as follows:

```ruby
create_table :businessmen do |t|
  t.string :name
  t.string :type
  t.timestamps null: false
end

# app/models/businessman.rb
class Businessman < ActiveRecord::Base
  has_paper_trail
end

# app/models/businessman/product.rb
class Businessman::Product < Businessman
  has_paper_trail
end
```

Now that we know more about this issue, I don't think we can support this use case. I will close this issue.

In general, it's probably a bad idea for `Product` to extend `Businessman` **and** be namespaced under `Businessman`. Try removing the namespacing.

It is also a questionable decision to have `Product` extend `Businessman` in the first place, because in the real world, a product is not a type of man. Class inheritance should mirror the real world. I recommend reading [Practical Object-Oriented Design in Ruby][2] which covers this well.

[1]: https://github.com/rails/rails/blob/70d1b5a7f8e25b077168deaf592e0e58c3f2bdd1/activerecord/lib/active_record/inheritance.rb#L100
[2]: http://www.poodr.com/

**Closed by jaredbeck** 2016-03-30 19:40 UTC
Labels: Confirmed Bug
