### ISSUE TITLE
paper_trail 4 breaks request_store

### ISSUE THREAD

**Issue by obduk** [airblade/paper_trail#646] opened 2015-11-10 16:10 UTC
In my application I use paper_trail 3 and request_store. When I upgrade to paper_trail 4 it breaks where I am using request_store.

I have tried digging around the paper_trail and request_store code but cannot quite figure out why yet?

This is my pull request on my project https://github.com/obduk/cms/pull/376

This is the the only places in my project where I am using request_store:
* https://github.com/obduk/cms/blob/master/app/controllers/application_controller.rb#L47
* https://github.com/obduk/cms/blob/master/app/models/user.rb#L94

Sorry I can't find out the specific error...

**Comment by obduk** [comment] 2015-11-10 16:12
The reason the tests are failing is the the line in the model is returning `nil`.

**Comment by batter** [comment] 2015-11-10 16:19
Is this reproducible on your local? As in, does this happen consistently?

**Comment by obduk** [comment] 2015-11-10 16:27
Yes it happens locally as well, and happens consistently

**Comment by jaredbeck** [comment] 2015-11-10 17:05
What steps can we take to reproduce this error in a brand new rails app?

**Comment by jaredbeck** [comment] 2015-11-27 21:45
@obduk we don't have enough information to reproduce this issue. What steps can we take to reproduce this error in a brand new rails app?

**Comment by obduk** [comment] 2015-12-01 15:35
Sorry, I have not had time to look at this, will try and do next week.

**Comment by jaredbeck** [comment] 2015-12-16 16:31
Closing due to lack of information.  Please provide the requested information and we'll be happy to reopen this issue.

**Closed by jaredbeck** 2015-12-16 16:31 UTC
Labels: Need Information
