### ISSUE TITLE
Update to a record which is not included in default scope

### ISSUE THREAD

**Issue by LeKristapino** [airblade/paper_trail#866] opened 2016-09-13 21:33 UTC
Hi, thanks for the great gem.

One problem I noticed is that is is not possible to have a model with default scope and update a record of that model to not be included in the default scope

```
  Class Entry < ApplicationRecord
  # has a db column "deleted"
    def self.default_scope
      where(deleted: false)
    end
  end
```

When doing 

`Entry.first.update_attribute(:deleted, true)` I get an error:

`NameError: undefined local variable or method 'id' for #<PaperTrail::RecordTrail:0x007f960b8402d0>`

As far as I have investigated, the problem could be solved by using: `unscoped` when paper trail is searching for the record. But I am not sure if that won't break other funcionality you guys have..

**Comment by jaredbeck** [comment] 2016-09-13 23:19
> Hi, thanks for the great gem.

Glad you like it ❤️ 

I'm not sure about your specific situation, but [we discussed `default_scope` generally back in December][1] and came to the conclusion that PT will respect default scopes. In other words, we decided that PT will not use `unscoped`.

That said, I feel like your code should still work. Can you reproduce the issue using our [bug report template][2]?

[1]: https://github.com/airblade/paper_trail/issues/671
[2]: https://github.com/airblade/paper_trail/blob/master/doc/bug_report_template.rb

**Comment by LeKristapino** [comment] 2016-09-16 21:49
It seems that it works if I use the template.. :/ Ok, will look deeper for the cause of the error

**Comment by jaredbeck** [comment] 2016-09-17 01:53
> It seems that it works if I use the template ..

Thanks for trying Kristaps. I'll close this for now, but let us know if you can reproduce the issue using the template and we'll re-open this issue. Thanks!

**Closed by jaredbeck** 2016-09-17 01:53 UTC
Labels: Need Information

**Comment by duffyjp** [comment] 2017-06-08 19:11
I'm having a similar issue after upgrading to Rails 5.1.  I'm also struggling to reproduce the issue with the template.

The one difference that's nagging me between my App and the template is that I have this in my paper_trail initializer (since paper_trail 3). 
```ruby
PaperTrail::Rails::Engine.eager_load! 
```

Without it I get this: 
```ruby
 undefined method `relation_delegate_class' for PaperTrail::Version:Class
```

Now in the template, I can't call it, I get 
```ruby
uninitialized constant PaperTrail::Rails (NameError)
```

The `eager_load!` line hasn't been in the Readme for a while, for what that's worth.

----------

### Since I can't reproduce it yet, let me describe the issue a little better-- 

| Rails | PaperTrail | Status |
------|------------|--------
5.0.3 | 7.0.2 | pass
5.1.1 | 7.0.3 |  fail

Model: 
```ruby
class MailingList < ActiveRecord::Base
  has_paper_trail ignore: :updated_at
  validates     :name, presence: true, uniqueness: true
  default_scope { where(active: true).order(:name) }
end
```

Test:
```ruby
  let(:mailing_list) { create :mailing_list }
  it "changing something stores a version" do
    expect(mailing_list.reload.versions.count).to eq(1)   # event: create
    mailing_list.update(active: false)
    expect(mailing_list.reload.versions.count).to eq(2)   # event: create, update
  end
```

Log:
```
  MailingList Exists (0.3ms)  SELECT  1 AS one FROM `mailing_lists` WHERE `mailing_lists`.`name` = BINARY 'likes.tacos.1' LIMIT 1
  SQL (0.2ms)  INSERT INTO `mailing_lists` (`name`, `created_at`, `updated_at`) VALUES ('likes.tacos.1', '2017-06-08 17:36:50', '2017-06-08 17:36:50')
  MailingList Load (0.4ms)  SELECT  `mailing_lists`.* FROM `mailing_lists` WHERE `mailing_lists`.`active` = 1 AND `mailing_lists`.`id` = 1 ORDER BY `mailing_lists`.`name` ASC LIMIT 1
  SQL (0.3ms)  INSERT INTO `versions` (`item_type`, `item_id`, `event`, `created_at`) VALUES ('MailingList', 1, 'create', '2017-06-08 17:36:50')
   (0.1ms)  RELEASE SAVEPOINT active_record_1
  MailingList Load (0.2ms)  SELECT  `mailing_lists`.* FROM `mailing_lists` WHERE `mailing_lists`.`id` = 1 LIMIT 1
   (0.3ms)  SELECT COUNT(*) FROM `versions` WHERE `versions`.`item_id` = 1 AND `versions`.`item_type` = 'MailingList'
   (0.2ms)  SAVEPOINT active_record_1
  MailingList Exists (0.4ms)  SELECT  1 AS one FROM `mailing_lists` WHERE `mailing_lists`.`name` = BINARY 'likes.tacos.1' AND (`mailing_lists`.`id` != 1) LIMIT 1
  SQL (0.3ms)  UPDATE `mailing_lists` SET `active` = 0 WHERE `mailing_lists`.`id` = 1
  MailingList Load (0.3ms)  SELECT  `mailing_lists`.* FROM `mailing_lists` WHERE `mailing_lists`.`active` = 1 AND `mailing_lists`.`id` = 1 ORDER BY `mailing_lists`.`name` ASC LIMIT 1
Unable to create version for update of MailingList#1: Item must exist
   (0.1ms)  RELEASE SAVEPOINT active_record_1
  MailingList Load (0.2ms)  SELECT  `mailing_lists`.* FROM `mailing_lists` WHERE `mailing_lists`.`id` = 1 LIMIT 1
   (0.3ms)  SELECT COUNT(*) FROM `versions` WHERE `versions`.`item_id` = 1 AND `versions`.`item_type` = 'MailingList'
   (1.2ms)  ROLLBACK
```

> Unable to create version for update of MailingList#1: Item must exist


```
     Failure/Error: expect(mailing_list.reload.versions.count).to eq(2)   # event: create, update
     
       expected: 2
            got: 1
```

Here's my WIP [bug_report_template](https://gist.github.com/duffyjp/4db4c912111350cf894946d1d9ab679a) . I'll bump the thread if I can get a failure.   Thanks.

**Comment by jaredbeck** [comment] 2017-06-08 19:23
> I'm also struggling to reproduce the issue with the template. ...
> I'll bump the thread if I can get a failure.

Thanks for your work trying to isolate the issue! Much appreciated.

> The one difference that's nagging me between my App and the template is .. PaperTrail::Rails::Engine.eager_load! 

Since 71453f3b1f we no longer recommend `eager_load!`.

```diff
diff --git a/CHANGELOG.md b/CHANGELOG.md
index 2c523a8..c046aea 100644
--- a/CHANGELOG.md
+++ b/CHANGELOG.md
@@ -2,9 +2,10 @@
 
 ### Changes
 
-- If you use a Rails initializer for PaperTrail add
-  `PaperTrail::Rails::Engine.eager_load!` to the beginning of it.
-  See the readme for an example.
+- Using a Rails initializer to reopen PaperTrail::Version or otherwise extend
+  PaperTrail is no longer recommended. An alternative is described in the
+  readme. See https://github.com/airblade/paper_trail/pull/557 and
+  https://github.com/airblade/paper_trail/pull/492.
```

Are you reopening `PaperTrail::Version` in your initializer?

**Comment by duffyjp** [comment] 2017-06-08 19:41
I am reopening PaperTrail::Version, we added the `person` method in 2013. :)


paper_trail.rb
```ruby
PaperTrail.config.track_associations = false      # https://github.com/airblade/paper_trail/issues/830
PaperTrail::Rails::Engine.eager_load!             # https://github.com/airblade/paper_trail/issues/392

module PaperTrail
  class Version
    def person
      User.find(whodunnit.to_i).try(:person) unless whodunnit.blank?
    end
  end
end
```

**Comment by jaredbeck** [comment] 2017-06-08 21:03
> I am reopening PaperTrail::Version [in my initializer]

OK, I think that's no longer recommended. Please try moving that to `app/models/paper_trail/version.rb` and you should be able to delete the `eager_load!`.
