### ISSUE TITLE
Issues with custom versions table names in 4.0.0.beta.2

### ISSUE THREAD

**Issue by bramswenson** [airblade/paper_trail#488] opened 2015-02-24 13:20 UTC
Occasionally In normal development environment, and regularly using `spring` it seems that PaperTrail 4.0.0.beta.2 looses track of the proper table name for version models. I have many version models in my rather large application. Each with its own table and custom class. `PaperTraill::Version` has been modified with  `self.abstract_class = true` and is only used as such. Since upgrading to 4.0.0.beta.2 if I reload the application from the console with `reload!` things go haywire. The fact that `reload!` can consistently reproduce the issue points some to why spring just wont work at all. This seems to be some type of preload/autoload issue. I'm pretty sure this would not manifest in production environments where code is not reloaded, but I could be wrong. Here is an example of the problem in action:

```shell
$ be rails console                                                                  ✹
Loading development environment (Rails 3.2.21)
[1] pry(main)> StoryTagVersion.count
   (0.3ms)  SELECT COUNT(*) FROM `dk4_dev_versions`.`story_tag_versions` 
=> 1
[2] pry(main)> reload!
Reloading...
   (0.5ms)  SELECT DATABASE() as db
   (0.4ms)  SELECT DATABASE() as db
   (0.5ms)  SELECT DATABASE() as db
   (0.4ms)  SELECT DATABASE() as db
   (0.4ms)  SELECT DATABASE() as db
   (0.3ms)  SELECT DATABASE() as db
=> true
[3] pry(main)> StoryTagVersion.count
ActiveRecord::StatementInvalid: Mysql2::Error: Table 'dk4_dev_versions.versions' doesn't exist: SHOW FULL FIELDS FROM `versions`
from .bundle/bundle/ruby/1.9.1/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:245:in `query
```

**Comment by bramswenson** [comment] 2015-02-24 13:51
This issue pretty much breaks my test suite since it reloads code (like pretty much all rails test suites). It runs fine for a while then everything starts failing due to the same type of exception as above.

**Comment by batter** [comment] 2015-02-24 15:23
See #483, I think that person may have more insight

**Comment by bramswenson** [comment] 2015-02-24 15:41
Interesting. I'm not using the `PaperTrail::Rails::Engine.eager_load!` statement as I am in rails 3.2 and the docs claim that it is not needed unless rails >= 4.0. I'm going to try a few more things and report back. Thanks for the info.

**Comment by bramswenson** [comment] 2015-02-24 16:53
Using 3.0.6 we did not explicitly use `self.table_name` in the version model definitions. Doing so made all my tests work again, but does not fix issues `reload!` or `spring`.

**Comment by batter** [comment] 2015-02-27 15:51
Actually, what the docs are trying to say is that the `PaperTrail::Rails::Engine.eager_load!` statement is needed for `PaperTrail` version `4.x`, but not for version `3.x`. The version of ActiveRecord / Rails being used is not relevant with regards to that.  So have you tried putting that statement at the top of your custom initializer?

**Comment by TobiasBales** [comment] 2015-03-02 17:10
I have the same issue.
beta2 with rails 4.2.0 but for me having self.table_name in my version models does not fix the issue.
The issue persists itself when modifying some code that force a reload in the dev environment.
So start server -> works -> save app/controllers/application_controller.rb -> reload -> does not work anymore

**Comment by jaredbeck** [comment] 2015-08-01 03:26
I think this is a duplicate of https://github.com/airblade/paper_trail/pull/492 and others like it.  We have addressed this issue by asking people to stop using an initializer.  We've found that initializers aren't compatible with `reload!`.  The new recommendation is given in the readme, and was added to the readme by https://github.com/airblade/paper_trail/pull/557.

**Closed by jaredbeck** 2015-08-01 03:26 UTC
