### ISSUE TITLE
Paper Trail not tracking Whodunnit column

### ISSUE THREAD

**Issue by andela-denoma** [airblade/paper_trail#921] opened 2017-01-18 14:45 UTC
We are using paper trail `4.0.0` and we make a lot of updates.

For some time now, Paper Trail does not store the whodunnit column. 

We have this in application controller

```
def user_for_paper_trail
    current_user.try(:email)
  end
```
What could be responsible for this? Is there a fix?

**Comment by jaredbeck** [comment] 2017-01-19 01:21
Hi Deborah, how cool to get a bug report from Lagos! 

Can you reproduce this problem in the latest version of PT (currently 6.0.2)? You may find our [bug report template](https://github.com/airblade/paper_trail/blob/master/doc/bug_report_template.rb) helpful for this. Thanks.

**Comment by jaredbeck** [comment] 2017-02-17 16:32
Closing due to insufficient information.

**Closed** 2017-02-17 16:32 UTC
Labels: Need Information
