### ISSUE TITLE
All versions have the same created_at value

### ISSUE THREAD

**Issue by khelll** [airblade/paper_trail#588] opened 2015-08-11 05:58 UTC
Every version gets created with the same created_at value of the first version.

This is my model:

```ruby
class Post < ActiveRecord::Base
  has_paper_trail only: [:title, :content, :link], on: [:update]
end
```

**Comment by jaredbeck** [comment] 2015-08-11 14:41
> Every version gets created with the same created_at value of the first version.

- Are you talking about the `versions.created_at` column, or the created_at value serialized in `versions.object`?
- What version of paper_trail are you using?
- What is the minimum code I can paste into a brand new rails app to reproduce this problem?

**Comment by ItaiLeibowitz** [comment] 2015-08-11 16:38
I believe I'm running into the same issue, using PaperTrail 4.0.0:

This is in `record_create`, where `data[PaperTrail.timestamp_field]` is set to the **item's created_at value**. The problem is, if the item was actually created at some point in the past and the current version is actually re-creating it (because it has also been deleted at some point), the version is getting a bad timestamp that is not in line with the current time of the update. 

Here's an illustration of the problem I'm getting because of this. I'm implementing an undo/redo mechanism:

Time=0: Item1.create    `=> (item1.created_at = 0; item1.updated_at = 0; version0.created_at = 0 )`
Time=1: Item1.update   `=>(Item1.created_at = 0; item1.updated_at = 1; version1.created_at = 1 )`
Time=2: item1.destroy  `=>(item1 = nil; version2.created_at = 2)`
Time=3: item1.create    `=>(item1.created_at = 0; item1.updated_at = 3; version3.created_at = 0)`

You can see that version3 has the wrong time stamp. It's a problem for me because `reify_has_many` still only uses timestamps to find subsequent versions, and my item1 is a has_many association. when I undo/redo, version3 never comes up in the `reify_has_many` query and that messes up the reification of associations.

One potential suggestion - it might be better to use the item's `updated_at` field for the timestamp - I think that would solve this problem:

````
def record_create 
[...]
  if respond_to?(:updated_at)
    data[PaperTrail.timestamp_field] = updated_at
  end
[...]
````

same as in the `record_update` method.

**Comment by khelll** [comment] 2015-08-11 18:43
I found the problem, turns out the method `updated_at` was redefined in the `Post` model. It seems that  the gem is making use of it to store the created_at for the version.

**Comment by batter** [comment] 2015-08-11 23:01
I believe PR #589 will address this if / when merged, correct?

**Comment by ItaiLeibowitz** [comment] 2015-08-11 23:03
Yes, exactly right.

**Closed** 2015-08-12 02:12 UTC
Labels: Need Information
