### ISSUE TITLE
Rails 3.0: uninitialized constant PaperTrail::Version

### ISSUE THREAD

**Issue by alexclarkofficial** [airblade/paper_trail#534] opened 2015-05-14 17:46 UTC
On Rails 3.0.3 with PaperTrail 4.0.0.rc.
Ran the following commands and was greeted with the error
```
bundle
bundle exec rails generate paper_trail:install
bundle exec rake db:migrate
rails c
```
The generator created one migration file `create  db/migrate/20150514161738_create_versions.rb`

**Comment by batter** [comment] 2015-05-14 18:48
Do you have a custom initializer for PaperTrail in your `config/initializers` directory?

**Comment by alexclarkofficial** [comment] 2015-05-14 18:59
Thanks for the quick reply!  I do not.  I tried creating one and placing the copying `lib/paper_trail/frameworks/active_record/models/paper_trail/version.rb ` into the file.  That changed my error to `uninitialized constant PaperTrail::VersionAssociation (NameError)`.

**Comment by batter** [comment] 2015-05-14 21:51
Can you provide the full stack trace please?

`rails c --trace`

**Comment by alexclarkofficial** [comment] 2015-05-14 21:58
Sure thing!
https://gist.github.com/alexclarkofficial/7184d199ddedf05fab3f
 We were actually able to get the app running with the following initializer:
```
class PaperTrail::VersionAssociation < ActiveRecord::Base
  include PaperTrail::VersionAssociationConcern
end

class PaperTrail::Version < ActiveRecord::Base
  include PaperTrail::VersionConcern
end 
```

**Comment by batter** [comment] 2015-05-14 22:25
What happens if you change the initializer to this?:

```ruby
require 'paper_trail/frameworks/active_record'
```

I'm wondering if the `Rails::Engine` eager loading doesn't work the same way on Rails `3.0.x` as it does on `3.1+`...

Also curious if you could give this initializer a whirl to see what happens?

```ruby
PaperTrail::Rails::Engine.eager_load!
```

lastly, could you try booting up the console and seeing what returns from this command?
```ruby
p  PaperTrail::Rails::Engine.paths['app/models'].instance_variable_get(:@paths)
```

Thanks for working with me. I'm wondering if [this class](https://github.com/airblade/paper_trail/blob/v4.0.0.rc1/lib/paper_trail/frameworks/rails/engine.rb) isn't performing how it normally does with that version of Rails for some reason.

**Comment by alexclarkofficial** [comment] 2015-05-15 16:00
Not a problem.  The first initializer gave this error when I started the console:
```
.rvm/gems/ruby-1.9.3-p551/gems/paper_trail-4.0.0.rc1/lib/paper_trail/config.rb:33:in `track_associations': uninitialized constant PaperTrail::VersionAssociation (NameError)
```
The second gave this:
```
config/initializers/paper_trail.rb:1:in `<top (required)>': undefined method `eager_load!' for PaperTrail::Rails::Engine:Class (NoMethodError)
```
And lastly here is the result for the console command(after using the initializer I sent over:
```
1.9.3-p551 :001 > PaperTrail::Rails::Engine.paths['app/models'].instance_variable_get(:@paths)
 => ["app/models"]
```

**Comment by batter** [comment] 2015-05-15 20:57
Interesting, seems like the models directory is not being loaded in properly in that case. I'm wondering if it's a Rails version number. Will push a commit up soon trying to address this.

**Comment by jaredbeck** [comment] 2015-06-26 20:34
> Will push a commit up soon trying to address this.

Ben, did that commit happen?  Were you able to reproduce the issue?

**Comment by batter** [comment] 2015-06-26 20:38
#554, which was merged, should fix the issue encountered that raised

`uninitialized constant PaperTrail::VersionAssociation (NameError)`

I'm still not certain what was causing the original issue. I need to setup a dummy app with an older version of Rails (3.0.x) to try to see if I can reproduce it.

**Comment by jaredbeck** [comment] 2015-07-23 05:04
Alex, I can reproduce this issue with rails 3.0.3 and paper_trail 4.0.0.rc2.

```
bundle
bundle exec rails generate paper_trail:install
bundle exec rake db:migrate
rails c
PaperTrail::Version
# NameError: uninitialized constant PaperTrail::Version
```

To clarify, rails 3.0.3 is not able to autoload the `PaperTrail::Version` constant.

Ben, given that rails 3.0 is EOL, and our test suite passes on rails 3.2, my instinct here is for paper_trail 4.0 to drop support for rails < 3.2.

Alex, is there any reason you need to use paper_trail 4.0 now, or can you just use paper_trail 3.x until you can upgrade to a non-EOL version of rails?

**Comment by batter** [comment] 2015-07-23 05:57
@jaredbeck - Not against that, however I think we could probably continue to support ActiveRecord 3.x by modifying [this block here](https://github.com/airblade/paper_trail/blob/master/lib/paper_trail.rb#L152) to read more like this:

```ruby
if defined?(::Rails) && ActiveRecord::VERSION::STRING >= '3.2'
  require 'paper_trail/frameworks/rails'
else
  require 'paper_trail/frameworks/active_record'
end
```

I don't really see a lot of harm in continuing to support it for the time being, but perhaps it would be asking for trouble, but I guess my thinking is sort of "until there is something that will definitely break it, why drop support". That being said I think there is a line that should be drawn somewhere...  I mean the gem also still supports Ruby 1.8 which is probably unnecessary as well, but again, I didn't see much reason to drop support since it generally mostly boils down to using the hash rocket syntax for hashes. :wink:

**Comment by jaredbeck** [comment] 2015-07-23 17:21
> .. I think we could probably continue to support ActiveRecord 3.x by modifying this block ..

Great!  Yeah, if there's a simple fix, I don't see any reason not to keep supporting rails 3.0.

**Comment by batter** [comment] 2015-07-23 18:16
It's worth a shot @alexclarkofficial, can you give cb10579 a try and see if that fixes your issue?

**Comment by alexclarkofficial** [comment] 2015-07-23 19:22
@batter Yes, can do! If I don't confirm by the Monday feel to ping me again.

**Comment by batter** [comment] 2015-08-04 15:41
@alexclarkofficial - Can you try the `4.0.0` release and confirm it fixes the issue you were seeing?

**Comment by alexclarkofficial** [comment] 2015-08-13 21:18
@batter Sorry for the hold up! Also sorry to report it failed even earlier... Simply having `'paper_trail'` in my `Gemfile` stopped Rails from booting. Here's the log trying to run the generator:

```
Alexanders-Air:mackey alexanderclark$ bundle exec rails generate paper_trail:install
Bundler is using a binstub that was created for a different gem.
This is deprecated, in future versions you may need to `bundle binstub railties` to work around a system/bundle conflict.
/Users/alexanderclark/.rvm/gems/ruby-1.9.3-p551/gems/activerecord-3.0.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:316:in `retrieve_connection': ActiveRecord::ConnectionNotEstablished (ActiveRecord::ConnectionNotEstablished)
	from /Users/alexanderclark/.rvm/gems/ruby-1.9.3-p551/gems/activerecord-3.0.3/lib/active_record/connection_adapters/abstract/connection_specification.rb:97:in `retrieve_connection'
	from /Users/alexanderclark/.rvm/gems/ruby-1.9.3-p551/gems/activerecord-3.0.3/lib/active_record/connection_adapters/abstract/connection_specification.rb:89:in `connection'
	from /Users/alexanderclark/.rvm/gems/ruby-1.9.3-p551/gems/activerecord-3.0.3/lib/active_record/base.rb:673:in `table_exists?'
	from /Users/alexanderclark/.rvm/gems/ruby-1.9.3-p551/gems/paper_trail-4.0.0/lib/paper_trail/config.rb:35:in `track_associations'
	from /Users/alexanderclark/.rvm/gems/ruby-1.9.3-p551/gems/paper_trail-4.0.0/lib/paper_trail/version_concern.rb:14:in `block in <module:VersionConcern>'
	from /Users/alexanderclark/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-3.0.3/lib/active_support/concern.rb:52:in `class_eval'
	from /Users/alexanderclark/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-3.0.3/lib/active_support/concern.rb:52:in `append_features'
	from /Users/alexanderclark/.rvm/gems/ruby-1.9.3-p551/gems/paper_trail-4.0.0/lib/paper_trail/frameworks/active_record/models/paper_trail/version.rb:5:in `include'
	from /Users/alexanderclark/.rvm/gems/ruby-1.9.3-p551/gems/paper_trail-4.0.0/lib/paper_trail/frameworks/active_record/models/paper_trail/version.rb:5:in `<class:Version>'
	from /Users/alexanderclark/.rvm/gems/ruby-1.9.3-p551/gems/paper_trail-4.0.0/lib/paper_trail/frameworks/active_record/models/paper_trail/version.rb:4:in `<module:PaperTrail>'
	from /Users/alexanderclark/.rvm/gems/ruby-1.9.3-p551/gems/paper_trail-4.0.0/lib/paper_trail/frameworks/active_record/models/paper_trail/version.rb:3:in `<top (required)>'
	from /Users/alexanderclark/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:239:in `require'
	from /Users/alexanderclark/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:239:in `block in require'
	from /Users/alexanderclark/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:225:in `block in load_dependency'
	from /Users/alexanderclark/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:596:in `new_constants_in'
	from /Users/alexanderclark/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:225:in `load_dependency'
	from /Users/alexanderclark/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:239:in `require'
	from /Users/alexanderclark/.rvm/gems/ruby-1.9.3-p551/gems/paper_trail-4.0.0/lib/paper_trail/frameworks/active_record.rb:4:in `<top (required)>'
	from /Users/alexanderclark/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:239:in `require'
	from /Users/alexanderclark/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:239:in `block in require'
	from /Users/alexanderclark/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:225:in `block in load_dependency'
	from /Users/alexanderclark/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:596:in `new_constants_in'
	from /Users/alexanderclark/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:225:in `load_dependency'
	from /Users/alexanderclark/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:239:in `require'
	from /Users/alexanderclark/.rvm/gems/ruby-1.9.3-p551/gems/paper_trail-4.0.0/lib/paper_trail.rb:155:in `<top (required)>'
	from /Users/alexanderclark/.rvm/gems/ruby-1.9.3-p551/gems/bundler-1.10.5/lib/bundler/runtime.rb:76:in `require'
	from /Users/alexanderclark/.rvm/gems/ruby-1.9.3-p551/gems/bundler-1.10.5/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
	from /Users/alexanderclark/.rvm/gems/ruby-1.9.3-p551/gems/bundler-1.10.5/lib/bundler/runtime.rb:72:in `each'
	from /Users/alexanderclark/.rvm/gems/ruby-1.9.3-p551/gems/bundler-1.10.5/lib/bundler/runtime.rb:72:in `block in require'
	from /Users/alexanderclark/.rvm/gems/ruby-1.9.3-p551/gems/bundler-1.10.5/lib/bundler/runtime.rb:61:in `each'
	from /Users/alexanderclark/.rvm/gems/ruby-1.9.3-p551/gems/bundler-1.10.5/lib/bundler/runtime.rb:61:in `require'
	from /Users/alexanderclark/.rvm/gems/ruby-1.9.3-p551/gems/bundler-1.10.5/lib/bundler.rb:134:in `require'
	from /Users/alexanderclark/mackeyRMS/mackey/config/application.rb:6:in `<top (required)>'
	from /Users/alexanderclark/.rvm/gems/ruby-1.9.3-p551/gems/railties-3.0.3/lib/rails/commands.rb:15:in `require'
	from /Users/alexanderclark/.rvm/gems/ruby-1.9.3-p551/gems/railties-3.0.3/lib/rails/commands.rb:15:in `<top (required)>'
	from script/rails:6:in `require'
	from script/rails:6:in `<main>'
```

**Comment by jaredbeck** [comment] 2015-08-14 13:54
> Simply having 'paper_trail' in my Gemfile stopped Rails from booting.

Can you reproduce this in a brand new rails 3.0.3 app, with papertrail 4.0.0?

**Comment by jaredbeck** [comment] 2015-08-21 06:17
Any new ideas here? Can we reproduce this in a brand new rails 3.0.3 app, with papertrail 4.0.0? 

Given the limited amount of time we have, I'd prefer to close this, and focus on versions of rails that are not EOL. However, Alex, if you have a solution, I think we'd love to have a PR.  Thanks.

**Comment by alexclarkofficial** [comment] 2015-08-21 11:38
Sorry, I actually changed jobs over the weekend and don't have a computer right now. Feel free to close.

**Closed** 2015-08-21 14:49 UTC
Labels: Need Information
