### ISSUE TITLE
creating versions when only associations change

### ISSUE THREAD

**Issue by nyon** [airblade/paper_trail#463] opened 2015-01-13 20:41 UTC
At first, I'd like to thank you for the great work you and all other contributers have spend on this gem.

I noticed, that no versions entry is generated when only the association data is changing. Is this the expected behaviour, or am I doing something wrong? I tried to write a little workaround which actually works now, but I would like to know, if there is some better way to achieve what I want to:

    before_save :check_change
    
    def check_change
      if Proc.new { |p| p.articles.map { |e| e.send(:changed_notably?) }.any? }
        self.updated_at = DateTime.now
      end
    end

Otherwise ```my_object.versions``` returns only the main model changes.
Is there some option I can pass to ```has_paper_trail``` to reproduce this functionality?

Best regards.

**Comment by theworkerant** [comment] 2015-01-14 01:36
:+1: I've got the same thing going on with one of my associations. Other nearly identical associations call `update_attribute` on the parent model for other reasons, but they work.

**Comment by batter** [comment] 2015-01-14 18:27
This is a dup of #461, and yes, that is the expected behavior.

I assume you are using the `4.0.0beta1` release?  For the time being, you can invoke `touch_with_version` to generate a new version on demand, but by next release (hopefully later today) I'm hoping to adjust it so you can just call `touch` and have a callback handle the version generating.

**Comment by theworkerant** [comment] 2015-01-20 14:41
Cool, for simplicity I'm looking to update versions manually in my app. If I wanted to do that could, how could I prevent auto-versioning? I've tried `has_paper_trail :on => [:update], :only => []` but that doesn't seem to do it. Will the work with `touch_with_version` make this possible so we can say `:on => [:touch]`?

**Comment by batter** [comment] 2015-01-20 21:14
Not yet. I'm debating what to do with the `touch` method.  There was an issue about this #329, and originally I had planned to just invoke the `after_touch` callback to have the normal `touch` method generate versions.  That being said, then that eliminates the option of invoking `touch` without generating a version.

Another alternative is to use something like `alias_method_chain` to override the default behavior for `touch` so it does generate a version, but then still have the method to generate without a version available named `touch_without_version`.  Still not sure how to handle that.  What do you think?

**Comment by theworkerant** [comment] 2015-01-21 13:36
I can't say I'm an expert on the ins and outs of `paper_trail` yet, but I feel overriding `touch` might be more confusing than not. I don't see/use `touch` very often, but I feel like it comes up in circumstances where you want to avoid things like the save callback cycle and have supreme control (could be wrong).

I don't see a problem with an explicit method like `touch_with_version` instead of trying to do magic on existing methods. In my use case I'd like this level of control without having to worry about other crazy stuff happening. However, I understand the case where people are expecting a version (#329). Perhaps this requires a configuration setting and the default should be the least surprising one?

**Comment by marnen** [comment] 2015-03-19 18:31
@theworkerant I can't recall ever having used `touch` for anything in 7 years of Rails development. I think working with the existing Rails callback infrastructure makes a lot more sense than having `touch_with_version` as a special case.

**Comment by robmathews** [comment] 2015-03-19 18:47
The current implementation of touch_with_version calls "save!".

This is unlike the official implementation of touch, which only:

    Saves the record with the updated_at/on attributes set to the current time. Please note that no validation is performed and only the after_touch, after_commit and after_rollback callbacks are executed.

So in our case, we added :touch=>true  to the belongs_to for a child object. Because our parent object had an after_save callback that updated some field sin the child object and thus caused a save in the child object, we got into an infinite loop on save.

I'd say that is a strong argument for not having touch_with_version call #save!

**Comment by batter** [comment] 2015-03-19 19:37
@robmathews - the implementation I came up with is a cross between the implementation that existed in [ActiveRecord 2.3](https://github.com/rails/rails/blob/2-3-stable/activerecord/lib/active_record/timestamp.rb#L27) (which did call `save!`), and the implementation that existed in [ActiveRecord 3.x](https://github.com/rails/rails/blob/v3.2.21/activerecord/lib/active_record/persistence.rb#L320).

I'd say you are correct that it should probably be brought up to date w/ the current implementation that exists in modern versions of ActiveRecord for PaperTrail 4..

**Comment by robmathews** [comment] 2015-03-19 19:58
Hiya @batter!

Not sure what you mean "brought up to date", I'm reading the code in master as of today. It looks like this: 

      def touch_with_version(name = nil)
        raise ActiveRecordError, "can not touch on a new record object" unless persisted?

        attributes = timestamp_attributes_for_update_in_model
        attributes << name if name
        current_time = current_time_from_proper_timezone

        attributes.each { |column| write_attribute(column, current_time) }
        save!
      end

I suspect we'd need to change the code to be an after_touch callback and in the after_touch go off and create a version, along the lines of this code:

          version = self.class.paper_trail_version_class.create(merge_metadata(data))

**Comment by batter** [comment] 2015-03-20 18:48
I say "brought up to date" because the [implementation in modern versions of rails has changed](https://github.com/rails/rails/blob/v4.2.1/activerecord/lib/active_record/persistence.rb#L453).  Realistically I thought about it and I think we're better off having a `touch_with_version` method, and if users want to have `touch` generate versions for their models they can add their own `after_touch` callback to call `touch_with_version` (or override the `touch` method).  Do you think that sounds like a good middle ground?

**Comment by robmathews** [comment] 2015-03-20 19:35
Agreed!

**Comment by onordgren** [comment] 2015-03-25 08:26
Hello, I have used the touch_with_version in one of my model in the after_touch callback like so `after_touch :touch_with_version` and its working very well. I however noticed a problem when I tried to save one of the associated models. If the associated model has any validation errors the whole transaction will be halted which I believe is not the intended behaviour, at least not compared to the regular touch method where no validations are run.

**Comment by batter** [comment] 2015-04-10 03:08
@onordgren - Thanks for the feedback, I think you're dead on, c7f94340e857af19cccb2c891999bf18f490bcd6 will make `touch_with_version` run without validations just like the `touch` method.

**Comment by batter** [comment] 2015-04-10 03:20
@robmathews, you could roll your own custom solution by adding this to one of your models:

```ruby
class Widget
  has_paper_trail on: [:touch]
  after_touch { |m| m.send(:record_update, true) } if paper_trail_options.fetch(:on, {}).fetch(:touch, true)
end
```

Or something to that effect.  The downside is that since the callback would then be triggered by an actual touch action, you don't get the timestamp you should inside the version... it will give the timestamp AFTER the touch occurs instead of the one prior to the touch being invoked like we do with normal updates.  Not sure of the ramifications of this, but that's why we can't properly take advantage of the `after_touch` callback right now (unless I'm missing something). Now on the other hand a `before_touch` callback would in theory work fine.

**Comment by tbogart** [comment] 2015-05-13 23:03
Related scenario (to this and request #508): I'm paper_trailing A which has_many B. Whenever there are changes to any of the Bs, I want to record a version for A. Typically, updates to a B are made via nested_attributes update to A, in which case I'd want my object_changes to look something like:

`{'a_attr1' => [1, 2], 'a_attr2' => [3, 4], 'b' => [nil, nil]}`

where in this case, the 'b' => [nil, nil] would be my own custom representation of: "something changed in the B association, though I don't really care what".

One approach: define a new public method in has_paper_trail like 'track_extra_object_changes', which if invoked with a non-empty hash:
- Forces a version to be created in the usual record_create/record_update flow, even if it seems nothing has notably changed
- Merges this hash into the changes generated for object_changes

Then I can just call
`track_extra_object_changes({'b' => [nil, nil]})`
at any point in my AR callback flow (in the case of the nested_attrs update, after_update should work well, but it could also be used after_touch).

I can PR this if it sounds useful to anyone else, but I'll be interested to see first where you land with the touch_with_version changes.

Thanks - gem's been working great for us.

**Comment by robmathews** [comment] 2015-05-14 12:31
Can't you just add ":touch=>true" to the belongs_to association on B?

**Comment by tbogart** [comment] 2015-05-14 17:44
Yeah, I do already have that in the association; it's a little tricky capturing this touch in the right spot in the callback flow, so that it can be versioned simultaneously with updates to the A attributes in a nested_attributes update, but I'm sure there's a way.

The bigger issue is what gets recorded in object_changes - I want to know that something in the Bs changed, not just that A.updated_at changed.

**Comment by shaneog** [comment] 2015-06-19 23:51
Will this continue to delay the 4.0 release?

**Comment by Jakeah** [comment] 2015-09-08 17:44
I'm trying to do the same thing as @tbogart and would be happy with each of the associated model's object changes being thrown in to that version.  It's been "interesting" trying to get the has_many association updates correlated with the model for an activity log.

**Comment by davidham** [comment] 2015-10-09 16:34
Hi, I'm working on an app where I need to show the audit trail on a Record, which has_many Data. I have paper_trail on my Record, and associated Datum models, and it is saving versions of them just fine. 

However, what I need is for **one** version for Record to be created whenever **one or more** associated Data are changed. I put `touch_with_version` in the `after_touch` callback on my Record, and it fires, but unfortunately it creates a new version for each Data, so when a Record is created it already has like 10 versions, one for each Datum.

Is there a way to tell in the callbacks if a version has been created, so I don't create multiples? Happy to post to SO if that's more appropriate.

**Comment by jaredbeck** [comment] 2015-10-10 04:28
Closing; this seems to have been answered pretty thoroughly by Ben back in April.

David, for your question, yes, per our (new) [contributing guide](https://github.com/airblade/paper_trail/blob/master/CONTRIBUTING.md) we'd prefer that you ask usage question on SO. If you do find a bug though, we definitely want to hear about it here on GH issues, thanks!

**Closed by jaredbeck** 2015-10-10 04:28 UTC
Labels: Not a bug

**Comment by davidham** [comment] 2015-10-11 16:42
Here's my SO in case others are trying to solve this problem: http://stackoverflow.com/questions/33043447/paper-trail-create-a-version-on-parent-whenever-associated-model-changes

**Comment by tomoyuki28jp** [comment] 2015-12-16 07:15
Nobody has answered @davidham's SO question yet. I've asked a similar question. I'm glad if anyone can answer it.
[What's the right way to list all versions of a record including its associations?](http://stackoverflow.com/questions/34305935/whats-the-right-way-to-list-all-paper-trail-versions-including-associations)

**Comment by Jakeah** [comment] 2015-12-16 15:34
I posted an imperfect answer SO.

http://stackoverflow.com/questions/34305935/whats-the-right-way-to-list-all-paper-trail-versions-including-associations/34315902#34315902

**Comment by tomoyuki28jp** [comment] 2015-12-19 16:44
I try something like @nyon's code.

```ruby
class Place < ActiveRecord::Base
  has_paper_trail
  has_many :place_names
  before_update :check_change

  def check_change
    place_names.each do |r|
      if r.send(:changed_notably?)
        self.updated_at = DateTime.now
        return
      end
    end unless changed_notably?
  end
end

class PlaceName < ActiveRecord::Base
  has_paper_trail
  belongs_to :place
end
```

When I update Place with new PlaceName, extra update version is created for PlaceName. Any idea why?

```ruby
Version.last # => #<Version id: 1531, item_type: "PlaceName", event: "update" ... >
Version.last.changeset # => {"created_at"=>[2015-12-19 16:23:27 UTC, 2015-12-19 16:23:27 UTC], "updated_at"=>[2015-12-19 16:23:27 UTC, 2015-12-19 16:23:27 UTC]}
```
